version: "3"

services:
  node1:
    image: axelar/core
    container_name: axelar-node-1
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.11"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-1
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.9
    - NODE_MONIKER=massbit-validator-1
    volumes:
    - ./home/node1:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh
  
  node2:
    image: axelar/core
    container_name: axelar-node-2
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.12"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-2
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.9
    - NODE_MONIKER=massbit-validator-2
    volumes:
    - ./home/node2:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh
  
  node3:
    image: axelar/core
    container_name: axelar-node-3
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.13"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-3
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.9
    - NODE_MONIKER=massbit-validator-3
    volumes:
    - ./home/node3:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh
  
  node4:
    image: axelar/core
    container_name: axelar-node-4
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.14"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-4
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.9
    - NODE_MONIKER=massbit-validator-4
    volumes:
    - ./home/node4:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh

networks:
  massbit:
    external: true