version: "3"

services:
  evm-local:
    image: evm-local
    container_name: evm-local
    command: sh "/app/start.sh"
    networks:
      massbit:
        ipv4_address: "172.24.97.100"
    volumes:
    - ./home/evm/chain-config:/app/chain-config
    ports:
      - 3009:3000
      - 8500:8500

  node1:
    image: axelar/core
    container_name: axelar-node-1
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.11"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-1
    - BROADCASTER_NAME=massbit-broadcaster-1
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.21
    - NODE_MONIKER=massbit-validator-1
    volumes:
    - ./home/node1:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh
    - ./init-validator.sh:/init-validator.sh
    - ./register-external-chain.sh:/register-external-chain.sh
  
  tofnd1:
    container_name: tofnd1
    hostname: tofnd1
    networks:
      massbit:
        ipv4_address: "172.24.97.21"
    image: axelar/tofnd
    volumes:
      - ./home/node1/.tofnd:/.tofnd
    environment:
      - MNEMONIC_CMD=auto
    user: root
  
  node2:
    image: axelar/core
    container_name: axelar-node-2
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.12"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-2
    - BROADCASTER_NAME=massbit-broadcaster-2
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.22
    - NODE_MONIKER=massbit-validator-2
    volumes:
    - ./home/node2:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh
    - ./init-validator.sh:/init-validator.sh
    - ./register-external-chain.sh:/register-external-chain.sh
  
  tofnd2:
    container_name: tofnd2
    hostname: tofnd2
    networks:
      massbit:
        ipv4_address: "172.24.97.22"
    image: axelar/tofnd
    volumes:
      - ./home/node2/.tofnd:/.tofnd
    environment:
      - MNEMONIC_CMD=auto
    user: root
  
  node3:
    image: axelar/core
    container_name: axelar-node-3
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.13"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-3
    - BROADCASTER_NAME=massbit-broadcaster-3
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.23
    - NODE_MONIKER=massbit-validator-3
    volumes:
    - ./home/node3:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh
    - ./init-validator.sh:/init-validator.sh
    - ./register-external-chain.sh:/register-external-chain.sh
  
  tofnd3:
    container_name: tofnd3
    hostname: tofnd3
    networks:
      massbit:
        ipv4_address: "172.24.97.23"
    image: axelar/tofnd
    volumes:
      - ./home/node3/.tofnd:/.tofnd
    environment:
      - MNEMONIC_CMD=auto
    user: root
  
  node4:
    image: axelar/core
    container_name: axelar-node-4
    # command: sleep infinity
    networks:
      massbit:
        ipv4_address: "172.24.97.14"
    environment:
    - KEYRING_PASSWORD=12345678
    - VALIDATOR_NAME=massbit-validator-4
    - BROADCASTER_NAME=massbit-broadcaster-4
    - CHAIN_ID=scalar
    - AXELARD_CHAIN_ID=scalar
    - TOFND_HOST=172.24.97.24
    - NODE_MONIKER=massbit-validator-4
    volumes:
    - ./home/node4:/home/axelard/.axelar
    - ./entrypoint.sh:/entrypoint.sh
    - ./init-validator.sh:/init-validator.sh
    - ./register-external-chain.sh:/register-external-chain.sh
  
  tofnd4:
    container_name: tofnd4
    hostname: tofnd4
    networks:
      massbit:
        ipv4_address: "172.24.97.24"
    image: axelar/tofnd
    volumes:
      - ./home/node4/.tofnd:/.tofnd
    environment:
      - MNEMONIC_CMD=auto
    user: root

networks:
  massbit:
    external: true